Console.WriteLine("Гири! Ищем самую тяжелую:");
int a = 4;
int b = 2;
int c = 9;
int d = 1;
int e = 5;
int f = 7;
int max = a;
if(a > max) max = a;
if(b > max) max = b;
if(c > max) max = c;
if(d > max) max = d;
if(e > max) max = e;
if(f > max) max = f;
Console.Write("Самая тяжелая гиря, кг: ");
Console.WriteLine(max);